### ISSUE TITLE
The old PHP version could handle URLs directly

### ISSUE THREAD

**Issue by tomnomnom** [tomnomnom/gron#1]
The new Go version should do that too. It's useful for trivial cases.

**Comment by iamthemovie** [comment]
I have a PR for this now :)

**Comment by tomnomnom** [comment]
Awesome, thanks! I'll review it this evening :)

**Comment by tomnomnom** [comment]
@iamthemovie I've issued a PR onto your master branch with a couple of changes I think I'd need before accepting, have a peek: iamthemovie/gron#1
