### ISSUE TITLE
gron will fail to link at runtime once OpenBSD removes syscall(2)

### ISSUE THREAD

**Issue by jrick** [tomnomnom/gron#114]
I currently see this running gron's master branch on a patched OpenBSD without syscall(2):

```
$ ./gron
gron:./gron: undefined symbol 'syscall'
ld.so: gron: lazy binding failed!
Killed 
```

The necessary fixes to use the proper libc stubs instead of the syscall(2) interface have already made their way to gron's dependencies, but gron is not requiring new enough versions yet.  Bumping the `color` module to its latest version (1.15.0) resolves the issue.

**Comment by lafrenierejm** [comment]
Hey @jrick. This original repo seems to be unmaintained. I have made some significant changes on [my fork](https://github.com/lafrenierejm/gron), including an update to the `color` module. If you want to give that branch a spin, I'd be glad to field bug reports or feature requests if you send them over there.

**Comment by tomnomnom** [comment]
Apologies for my extended hiatus. The dependencies have now been updated and this should be resolved :)
