### ISSUE TITLE
Ungron to ignore lines saying --

### ISSUE THREAD

**Issue by marcusatbang** [tomnomnom/gron#15]
Grep can search for lines immediately preceding or following the matched line, using `grep -A`, `grep -B` or `grep -C`. However the output of these includes separator lines that read `--`. This output currently produces an error when you try to ungron the result.

Since grep is a primary use for gron, I believe it would be a useful enhancement for it to accept a common output of grep. It doesn't need to do anything with the lines, only match and exclude them.

For example:

```sh
$ gron file.json | grep -A 1 'ktoe per year'
```
```javascript
json.resources.geothermal.production.units = "ktoe per year";
json.resources.geothermal.production.value = 2007.738525390625;
--
json.resources.hydropower.production.units = "ktoe per year";
json.resources.hydropower.production.value = 9038.80078125;
--
json.resources.wind.production.units = "ktoe per year";
json.resources.wind.production.value = 381.5000305175781;
```

**Comment by tomnomnom** [comment]
Sounds like a good call to me!

It's workaround-able with a `grep -v '^--'` before the ungron, but it seems like it'd be a common enough occurrence to be worthwhile implementing.

I'll have a look at implementing it this evening, unless someone beats me to it of course :)

Thanks for the suggestion!

**Comment by tomnomnom** [comment]
@marcusatbang sorry it took so long!

Version [0.3.2](https://github.com/tomnomnom/gron/releases/tag/v0.3.2) should now not have this problem :)

**Comment by marcusatbang** [comment]
That was remarkably fast. Well done.

**Comment by marcusatbang** [comment]
Confirmed as working.

**Comment by tomnomnom** [comment]
Fantastic! Glad to hear it :)
