### ISSUE TITLE
Errors are opaque

### ISSUE THREAD

**Issue by tomnomnom** [tomnomnom/gron#16]
Errors reported to the user don't provide much help. E.g. `Fatal (failed to parse input statements)`

It would be good to provide more context, like where the problem was found.

**Comment by marcusatbang** [comment]
I was just about to raise this.

If you're concerned about changing the code's semantics, maybe you could add a `-v --verbose` flag that shows more detail in case of errors or warnings?

**Comment by tomnomnom** [comment]
I think there's a few things that need doing. Mostly I think the lexer needs to provide context for why something couldn't be parsed to help the user spot the problem.

Implicit in that is bubbling the cause back up to `main()`. Thinking about using https://github.com/pkg/errors to make that easier

**Comment by tomnomnom** [comment]
The state of affairs has improved slightly in 7dae2ae (included in [0.3.3](https://github.com/tomnomnom/gron/releases/tag/v0.3.3)) but there's still work to be done.

The lexer needs some attention now. There are some error conditions it could spot that are currently handled a layer higher where to context for the error isn't as readily available.
