### ISSUE TITLE
Sorting results

### ISSUE THREAD

**Issue by marcusatbang** [tomnomnom/gron#17]
When you need to compare two files (or parts of them) without caring about the order of values within an object, it's common to pipe the result of `gron` through `sort`. However, this is incorrect in cases where some values can span multiple lines.

For example:
```json
json.foo = "foo";
json.bar = "lorem ipsum dolor
sit amet consequetur
adipiscing elit";
```
These lines would be sorted on the command line like so:
```json
adipiscing elit";
json.bar = "lorem ipsum dolor
json.foo = "foo";
sit amet consequetur
```
This is obviously incorrect. The sorted output we want is:
```json
json.bar = "lorem ipsum dolor
sit amet consequetur
adipiscing elit";
json.foo = "foo";
```
It would be helpful if `gron` had an option to reliably sort the values as it outputs them, such as a `-s --sort` flag.

**Comment by tomnomnom** [comment]
The output of gron *should* be sorted already! There's a natural sort applied to the statements before they're outputted.

Is there a situation where the output isn't sorted reliably?

Also:  It shouldn't output things across multiple lines either (line breaks should be encoded as `\n`). Is there a situation where that's not true?

Thanks!

**Comment by tomnomnom** [comment]
This has prompted me to learn enough EBNF to make a proper spec / some railroad diagrams for what `gron --ungron` expects as its input: http://tomnomnom.github.io/gron/

**Comment by marcusatbang** [comment]
I'm going to have to investigate more. I was sure I saw split lines in the output before, and that `gron | sort | ungron` was therefore breaking; but can't reproduce it.

**Comment by marcusatbang** [comment]
I must have done something else and mistaken it for this issue. Closing until I can be more precise in my reporting.

**Comment by tomnomnom** [comment]
Thanks for the update :)

Fingers crossed that there's no actual problem!
