### ISSUE TITLE
(Very) Minor issue: gron version in header

### ISSUE THREAD

**Issue by gummiboll** [tomnomnom/gron#19]
Hello!

The User-Agent-header set in getURL has an outdated version number of gron. Instead of updating it manually it might be better if it's set from a const from main or something?

**Comment by tomnomnom** [comment]
That's a good idea.

It'd probably be best to set the value at build time via the ldflags `-X` option and make the release script set it to the tag. It'd be possible to add the version number to the help output / a `--version` option too then.

**Comment by tomnomnom** [comment]
Fixed and in the latest release: https://github.com/tomnomnom/gron/releases/tag/v0.3.3

Thanks again!

**Comment by gummiboll** [comment]
Well done!
