### ISSUE TITLE
Ungron doesn't work if a string contains only a backslash

### ISSUE THREAD

**Issue by doozr** [tomnomnom/gron#25]
Rather an edge case, this:

```
$ cat test.json 
{"nowork": "\\"}
$ gron test.json 
json = {};
json.nowork = "\\";
$ gron test.json | gron -u
ungron failed for `json.nowork = "\\";`: statement has no value
```

**Comment by tomnomnom** [comment]
Thanks for the report :)

This should be fixed as of f9157487e97a292cce332e28d7171d81f9f5badb

Looks like I'd previously tried to be clever instead of being clear.

I've not tagged a release for a while, so I think I'll do that shortly.
