### ISSUE TITLE
 gron won't connect to insecure https endpoints

### ISSUE THREAD

**Issue by jagsta** [tomnomnom/gron#26]
I'm unable to connect to https endpoints with self signed certificates due to the requirement to validate the server certificate with the default transport for net/http clients.

The ability to connect to insecure endpoints would be helpful, even if arguably not a good idea.

**Comment by tomnomnom** [comment]
Generally I'm against feature-bloat when there's a way around the problem (e.g. `curl -sk ... | gron`), but I think this is a common enough use-case (at least it is for me) to warrant implementing directly in gron.

**Comment by tomnomnom** [comment]
Fixed as of PR #27 - Thanks @jagsta!

**Comment by jagsta** [comment]
Thanks for the useful tool! it's made a horrible job with the graphite render api a lot easier this week :)

**Comment by tomnomnom** [comment]
no problemo :)

I've tagged and released 0.5.0 for ease of install: https://github.com/tomnomnom/gron/releases/tag/v0.5.0 :)
