### ISSUE TITLE
gronning APIs where an authentication token is needed

### ISSUE THREAD

**Issue by dpolychr** [tomnomnom/gron#29]
Dear Tom,

Many thanks for this very useful package which I already sent to people around as am sure they will find it extremely useful.
Would there be any way of trying this for APIs where authentication is needed? I tried for example and I get this message:

json = {};
json.detail = "Authentication credentials were not provided.";

Best wishes,
Dimitris

**Comment by tomnomnom** [comment]
Hi @dpolychr! Thanks for raising an issue :)

The HTTP client built into gron is very basic and doesn't really support those kinds of use-cases.

Where you need to make more complex requests I recommend you use a tool like `curl` to make the request, and pipe the output to gron.

For example:

```
▶ curl -s https://httpbin.org/anything -H'Authorization: Bearer 123qksdrfkj' | gron | grep headers
json.headers = {};
json.headers.Accept = "*/*";
json.headers.Authorization = "Bearer 123qksdrfkj";
json.headers.Connection = "close";
json.headers.Host = "httpbin.org";
json.headers["User-Agent"] = "curl/7.47.0";
```

One thing that can be particularly useful in cases such as these is Chrome's [copy as curl](https://developers.google.com/web/updates/2015/05/replay-a-network-request-in-curl) option in the DevTools.

Let me know if you have any issues with this approach and I'll try my best to help

**Comment by tomnomnom** [comment]
@dpolychr were you able to solve your issue using curl? :)

**Comment by dpolychr** [comment]
yeah @tomnomnom, many many thanks :-)

Best wishes,
Dimitris

**Comment by kakrona55** [comment]
Interesting

**Comment by kakrona55** [comment]
Interesting

**Comment by kakrona55** [comment]
Great
