### ISSUE TITLE
preserving JSON order

### ISSUE THREAD

**Issue by laowantong** [tomnomnom/gron#34]
Nice tool, really... But I was surprised that the `--no-sort` option doesn't seem to preserve the order of the keys in the input file. When I generate JSON files, I generally specify [my own custom order](https://github.com/laowantong/customsort). Working on a JSON file where, for instance, the first name always precedes the family name, makes a lot of things easier to check or modify inside a text editor.

Is it possible to make `--no-sort` preserve the original order? Ideally, ungroning would keep this order too.

Thanks!

**Comment by tomnomnom** [comment]
Hi @laowantong! Thanks for raising an issue!

Sadly that is a limitation of Go itself. Maps (akin to JSON objects) in Go are unordered. Because JSON objects are converted to Go maps, they lose any ordering that was in the input. This behaviour is ordinarily fine because the [JSON RFC](https://tools.ietf.org/html/rfc8259) defines objects to be unordered.

gron sorts its output by default only to ensure that a given input will always produce the same output.

I'm sorry but I won't be able to fix this for you :(

**Comment by laowantong** [comment]
Thanks for your quick and instructive reply. I think I will try to write a Python version of your tool (at least in the direction json -> gron), since Python has an `OrderedDict` type which can be [used with the JSON decoder](https://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict).

Keep up the good work!

**Comment by tomnomnom** [comment]
@laowantong no worries; sorry I couldn't be of more help!

The [original version of gron](https://github.com/tomnomnom/gron/blob/master/original-gron.php) from about 6 years ago was written in PHP and preserves the order IIRC; hah. That too only does the json -> gron mode and not much else.

**Comment by zmorris** [comment]
@tomnomnom I also vote to make preserving the original order an option, even though the JSON RFC says objects are unordered (I also vote that the JSON RFC spec is wrong hah).  Simplest example of why this issue will make working with data in the real world difficult:

```
$ echo '{"a": 1, "c": 3, "b": 2}' | gron --no-sort
json = {};
json.c = 3;
json.b = 2;
json.a = 1;
$ echo '{"a": 1, "c": 3, "b": 2}' | gron --no-sort
json = {};
json.a = 1;
json.c = 3;
json.b = 2;
```

The inconsistent output means we can't do the JSON -> gron -> JSON transform reliably, even if `--no-sort` worked for the `-u` option (as far as I can tell, it doesn't):

```
$ echo '{"a": 1, "c": 3, "b": 2}' | gron --no-sort | gron --no-sort -u
{
  "a": 1,
  "b": 2,
  "c": 3
}
```

I would even go as far as to vote that the Go spec is wrong (for the vast majority of human use cases, mathematical elegance arguments aside), and that Go maps should be ordered by last insertion just like PHP maps.

I fully understand the argument that alphabetic sorting is "good enough" to produce consistent output.  But it's just not useful for large JSON trees where keys like `end` are at the top and `start` are at the bottom, when the original JSON had them as the first two keys in the object.  I just don't have time to be scrolling around like that to find keys in the real world.  Could you use something like https://github.com/maurice2k/orderedmap to preserve order, and make `--no-sort` the default?

Other than that, thanks for your hard work on gron.

**Comment by c0b** [comment]
> Sadly that is a limitation of Go itself. Maps (akin to JSON objects) in Go are unordered. Because JSON objects are converted to Go maps, they lose any ordering that was in the input. This behaviour is ordinarily fine because the [JSON RFC](https://tools.ietf.org/html/rfc8259) defines objects to be unordered.

@tomnomnom Go's builtin Map indeed has that limitation, but it doesn't mean no way to resolve this problem in Go

in 2018 I wrote this article, compared 3 languages (Python, Javascript & Go)'s capability of handling JSON while preserving order of JSON object keys

https://medium.com/@ty0h/preserving-json-object-keys-order-in-javascript-python-and-go-language-170eaae0de03

and did a small `go-ordered-json` library on that,
https://gitlab.com/c0b/go-ordered-json
https://pkg.go.dev/gitlab.com/c0b/go-ordered-json?tab=importedby   (and did not notice till today that it gained some users :-) )

Clearly there are people who care about the capability of preserving JSON order, especially those who are writing tools like `jq` (in C) and this `gron`, I don't like the Golang official's attribute of **Abandoning** the PR who did it in 2015; hence I did not try to push it to official Golang at all;   Like Python has regular unordered dict and the OrderedDict, I personally think Go should have a OrderedMap implementation in the core, if not like @zmorris said to make Ordered map as default (like in JavaScript and PHP, but I'm personally not familiar about PHP);

2.
   from this thread [*Preserving key order in encoding/json*](https://groups.google.com/forum/#!topic/golang-dev/zBQwhm3VfvU)
   and the [*Abandoned 7930: encoding/json: Optionally preserve the key order of JSON objects*](https://go-review.googlesource.com/c/go/+/7930)

So this issue actually depends on if you really want this feature in gron, I think it's a required feature to have the capability to any tools playing with json format

If you want, you can reopen this, that I may be able to contribute a PR
