### ISSUE TITLE
awesome tool, less than awesome name

### ISSUE THREAD

**Issue by kplimack** [tomnomnom/gron#35]
grep + json = gron.  for a tool as useful as this one, can we get a better name ?

**Comment by tomnomnom** [comment]
@kplimack Glad you like the tool! I picked the name more than 5 years ago (when I didn't think anyone other than me would use it) so I'm pretty hesitant to change it. There's two hard things in computer science etc...

**Comment by kplimack** [comment]
only once delivery?
