### ISSUE TITLE
Document compatibility of json filters

### ISSUE THREAD

**Issue by plainas** [tomnomnom/gron#45]
I use this tool all the time to automate tasks over json APIs with shellscripts. It's the quickest way to get a working jq selector. Most of the times it works, but I take it that compatibility is not full.

It would be nice to have the limitations documented in the readme.

**Comment by tomnomnom** [comment]
Hi @plainas :)

Can you give me an example of the limitations you're referring to? I don't know of any JSON documents that gron is unable to handle

**Comment by plainas** [comment]
Well, it has actually worked for me. I don't know if I ever found a selector that is not jq compatible. If I did I can't recall it specifically. I was under the impression, from the discussions on hacker news when this was posted a while ago, that it was not intended to be fully compatible with jq. But maybe I got it wrong. Is it? Are the paths always valid jq selectors?

Hey, thanks for such useful tool.

**Comment by tomnomnom** [comment]
Ah, I think I misunderstood your original point sorry!

Compatibility with jq isn't a design goal for gron, but outputting valid JavaScript _is_ (by default at least). I'm not familiar enough with jq's selector syntax to know for sure if it's always compatible, but gron's output grammar is fairly simple, and is defined here if you want to see if it's likely to ever spit out anything that's incompatible: http://tomnomnom.github.io/gron/

I'm glad gron fits your use-case so far! Sorry I couldn't be of more help!
