### ISSUE TITLE
gron in Fedora

### ISSUE THREAD

**Issue by lkiesow** [tomnomnom/gron#69]
Hi @tomnomnom, thanks for the great tool. It was a great help to me on multiple occasions.

I just wanted to let you know that I've started the process of packaging gron for Fedora. It [is already accepted for the next release](https://src.fedoraproject.org/rpms/gron) and I'm hoping to get it in the current release in the next days. Once it's in, users will be able to just `dnf install gron`.

Let me know if you have any questions. If not, feel free to simply close this issue. Thanks, again, for creating gron.

**Comment by tomnomnom** [comment]
@lkiesow thank you so much for letting me know, and for getting it into Fedora! Things like this really help to make me feel like a "real" developer, thank you :)
