### ISSUE TITLE
Can't ungron strings containing both escapes and semi-colons

### ISSUE THREAD

**Issue by ConradIrwin** [tomnomnom/gron#7]
I was playing around with your tool on the output of gmail json, `gron` works fine, but I get an error "cannot parse input" if I try and pipe it back into `ungron`.

Narrowing it down, the problem seems to be reproducible with this example:

```
$ echo 'json.payload.headers[4].value = "from o1.email.codeship.io (o1.email.codeship.io. [192.254.119.116])        by mx.google.com with ESMTPS id d79si3761733ioj.86.2015.10.09.12.02.54        for \u003cconrad.irwin@gmail.com\u003e        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);        Fri, 09 Oct 2015 12:02:54 -0700 (PDT)";' | gron -u
Fatal (failed to parse input statements)
```

A little bit of digging reveals a minimal test case:

```
echo 'json.value = "\u003c ;"' | ./gron -u
```

It seems to be a combination of the character escape and the semi-colon in the string.

Let me know if I can be more helpful.

**Comment by tomnomnom** [comment]
Good spot! Thanks for the report. New version is incoming :)

**Comment by tomnomnom** [comment]
@ConradIrwin can you try v0.2.5 and confirm that fixes your problem?

https://github.com/tomnomnom/gron/releases/tag/v0.2.5

**Comment by tomnomnom** [comment]
Actually, I was a tad too hasty and I've introduced another problem as a result. Sorry about this!

**Comment by tomnomnom** [comment]
@ConradIrwin right! Let's try this again :laughing: 

0.2.7 should fix it - but without introducing a regression this time!

https://github.com/tomnomnom/gron/releases/tag/v0.2.7
