### ISSUE TITLE
When executed as “ungron” act as if —ungron passed

### ISSUE THREAD

**Issue by alblue** [tomnomnom/gron#77]
If you check your program name in gron, you can automatically enable ungron mode. See (eg) grep/egrep/fgrep which is the same binary but has a different behaviour depending on the program name.

**Comment by mikepurvis** [comment]
Note that doing this also helps package maintainers support the feature conveniently. For example in Debian, you just create `debian/links` in your packaging metadata, and the link will be managed as a part of the package.

**Comment by tomnomnom** [comment]
This is fixed now that #78 is merged. Thank you, @alblue :)
