### ISSUE TITLE
Please provide FreeBSD amd64 binary.

### ISSUE THREAD

**Issue by vermaden** [tomnomnom/gron#8]
As in topic.

**Comment by tomnomnom** [comment]
Will do! I'm just spinning up a freebsd machine to make sure the binary works fine and then I'll cut a release :)

**Comment by tomnomnom** [comment]
@vermaden there are now FreeBSD binaries available from 0.2.8:

https://github.com/tomnomnom/gron/releases/tag/v0.2.8

Let me know if you hit any problems with it.

**Comment by vermaden** [comment]
Thanks!Od: "Tom Hudson" &lt;notifications@github.com&gt;Do: "tomnomnom/gron" &lt;gron@noreply.github.com&gt;; Wysłane: 13:15 Środa 2016-08-03Temat: Re: [tomnomnom/gron] Please provide FreeBSD amd64 binary. (#8)Will do! I'm just spinning up a freebsd machine to make sure the binary works fine and then I'll cut a release :)
