### ISSUE TITLE
Add github topics?

### ISSUE THREAD

**Issue by jedahan** [tomnomnom/gron#88]
I forgot the name of this tool, and tried searching 'topic: json' and 'topic: cli', maybe those would help discoverability?

**Comment by dotcs** [comment]
Great idea. Besides the mentione `json` and `cli` topics, I'd also suggest to add [`terminal`](https://github.com/topics/terminal), [`command-line`](https://github.com/topics/command-line), [`shell`](https://github.com/topics/shell) and [`go`](https://github.com/topics/go)/[`golang`](https://github.com/topics/golang).

**Comment by tomnomnom** [comment]
Added, thank you :)
